id = "pico8-picotron-theme"
name = "Pico8 Picotron Theme (Zep Editor)"
version = "0.1.0"
schema_version = 1
authors = ["369px <tacoyinyang@gmail.com>"]
description = "A Pico8/Picotron inspired theme... call it Zep Editor :p"
repository = "https://github.com/369px/Zep-Editor"
